# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=400)),
                ('event_time', models.TimeField(auto_now_add=True)),
                ('related_division', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='patient.Patient')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('event_date', 'event_time')]),
        ),
    ]
