# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(blank=True, help_text='Enter Guardian Name if Patient is a minor', max_length=20, null=True)),
                ('relation_to_guardian', models.CharField(blank=True, help_text='Enter relationship to Guardian if Patient is a Minor', max_length=20, null=True, verbose_name='Relation')),
                ('guardian_phone', models.PositiveIntegerField(blank=True, null=True, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.BaseUser')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/patient')),
                ('username', models.CharField(blank=True, max_length=50, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('patient_section', models.CharField(blank=True, max_length=100, null=True, verbose_name='section')),
                ('patient_room', models.CharField(blank=True, max_length=100, null=True, verbose_name='room_num')),
                ('parent_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital')),
            ],
            bases=('hospital.baseuser',),
        ),
        migrations.AddField(
            model_name='guardian',
            name='patient_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
    ]
