# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Iran', max_length=200)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
                ('alley', models.CharField(blank=True, max_length=30, null=True)),
                ('building_no', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('user_type', models.IntegerField(choices=[(0, 'Receptionist'), (1, 'Boss'), (2, 'patient'), (3, 'systemAdmin'), (4, 'CasualUser'), (5, 'Pharmacy'), (6, 'Physician'), (7, 'Nurse')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Tel', models.CharField(blank=True, max_length=25, null=True)),
                ('ssn', models.CharField(max_length=9, null=True, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], default='Single', max_length=250, null=True)),
                ('marital_status_notes', models.CharField(blank=True, max_length=250, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Iran', max_length=200)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
                ('alley', models.CharField(blank=True, max_length=30, null=True)),
                ('building_no', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('father_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fax_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('hospital_Name', models.CharField(max_length=250)),
                ('hospital_Type', models.IntegerField(choices=[(0, 'public'), (1, 'private')])),
            ],
            bases=(models.Model, object),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.PositiveIntegerField(default=21)),
                ('phone_number', models.PositiveIntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_address', models.CharField(max_length=200)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.BaseUser')),
                ('staff_role', models.CharField(blank=True, choices=[('non_hospital_staff', 'Non Hospital Staff'), ('secretary', 'Secretary'), ('hospital_admin', 'Hospital Administrator'), ('hospital_staff', 'Hospital Staff'), ('nurse', 'Nurse'), ('physio', 'Physiotherapist'), ('doctor', 'Doctor')], help_text=' This is the Role of the Staff in the Hospital', max_length=100, null=True, verbose_name='Staff Role')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_staff_head', models.BooleanField(default=False, verbose_name='Is Staff Head of the Department')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital')),
            ],
            bases=('hospital.baseuser',),
        ),
        migrations.AddField(
            model_name='fax',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
        migrations.AddField(
            model_name='email',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
        migrations.AddField(
            model_name='address',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
    ]
