# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='ssn',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
