# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20171117_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_staff_head',
            field=models.BooleanField(default=False, verbose_name='Es jefe de departamento en el hospital'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('non_hospital_staff', 'Non Hospital Staff'), ('secretary', 'Secretary'), ('hospital_admin', 'Hospital Administrator'), ('hospital_staff', 'Hospital Staff'), ('nurse', 'Nurse'), ('physio', 'Physiotherapist'), ('doctor', 'Doctor')], help_text=' Este es el rol como parte del hospital', max_length=100, null=True, verbose_name='Staff Role'),
        ),
    ]
