# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.Staff')),
                ('specialty', models.CharField(choices=[('cr', 'cardialogist'), ('dr', 'dermatologist'), ('en', 'endocrinologist'), ('ent', 'ENT (Ear Nose Throat) Specialist'), ('ge', 'Gerontologist'), ('gy', 'Gynaecologist'), ('ha', 'Haematologist'), ('in', 'Internist'), ('ne', 'Neurologist'), ('ob', 'Obstetrician'), ('on', 'Oncologist'), ('op', 'Ophthalmologist'), ('or', 'Orthodontist'), ('ort', 'Orthopaedis'), ('pd', 'Pediatrician'), ('po', 'Podiatrist'), ('ra', 'Radiologist'), ('sr', 'Surgeon'), ('ur', 'Urologist')], max_length=3)),
                ('graduation_university_name', models.CharField(blank=True, max_length=200, null=True)),
                ('graduation_university_country', models.CharField(blank=True, max_length=200, null=True)),
                ('graduation_university_city', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(choices=[('DE', 'dentist'), ('GP', 'general practitioner'), ('SP', 'Specialist'), ('SSP', 'SSP')], max_length=2)),
            ],
            bases=('hospital.staff',),
        ),
    ]
